---
- name: Provision an EC2 server
  hosts: localhost
  connection: local

  vars:
    # Name of the VPC to provision the server into
    aws_ec2_vpc: ccm-vpc

    # Path to the public keypair to use
    aws_ec2_keypair: '~/.ssh/aws-educate-student.pub'

    # Instance provision details
    aws_ec2_placement:
      - count: 1
        size: t2.micro
        az: us-east-1a
        groups: ['ops', 'webservers']
        tags:
          Name: 'flask-api-1a'

      - count: 0
        size: t2.micro
        az: us-east-1b
        groups: ['ops', 'web']
        subnet:
          'tag:Tier': public
        tags:
          Name: 'bastion-1b'

      - count: 0
        size: t2.micro
        az: us-east-1c
        groups: ['ops', 'web']
        subnet:
          'tag:Tier': private
        tags:
          Name: 'bastion-1c'

    aws_ec2_groups:
      ops:
        description: SSH access to instances
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

      webservers:
        description: Webservers security group
        rules:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0

  roles:
     - role: Lowess.ec2
